### ISSUE TITLE
Pera Connect error with Reach.sh

### ISSUE THREAD

**Issue by fatihakdogan85** [perawallet/connect#126]
When we send transaction over Pera Connect using Reach.sh framework, we get the following error.

`reachsdk.min.js?7077:2 {type: 'signAndPost', e: TypeError: e.map is not a function
    at eval (webpack-internal:///./node_modules/@perawallet/conn…, es: 'TypeError: e.map is not a function'}e: TypeError: e.map is not a function
    at eval (webpack-internal:///./node_modules/@perawallet/connect/dist/index-96895f5f.js:2:18319)
    at Array.flatMap (<anonymous>)
    at exports.PeraWalletConnect.eval (webpack-internal:///./node_modules/@perawallet/connect/dist/index-96895f5f.js:2:18305)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///./node_modules/@perawallet/connect/dist/index-96895f5f.js:2:642)
    at new Promise (<anonymous>)
    at s (webpack-internal:///./node_modules/@perawallet/connect/dist/index-96895f5f.js:2:387)
    at exports.PeraWalletConnect.signTransaction (webpack-internal:///./node_modules/@perawallet/connect/dist/index-96895f5f.js:2:17885)
    at e.eval (webpack-internal:///./node_modules/@reach-sh/stdlib/dist/browser/reachsdk.min.js:3:2362860)
    at eval (webpack-internal:///./node_modules/@reach-sh/stdlib/dist/browser/reachsdk.min.js:3:2361552)
    at Object.eval [as next] (webpack-internal:///./node_modules/@reach-sh/stdlib/dist/browser/reachsdk.min.js:3:2361657)
    at s (webpack-internal:///./node_modules/@reach-sh/stdlib/dist/browser/reachsdk.min.js:3:2360371)message: "e.map is not a function"stack: "TypeError: e.map is not a function\n    at eval (webpack-internal:///./node_modules/@perawallet/connect/dist/index-96895f5f.js:2:18319)\n    at Array.flatMap (<anonymous>)\n    at exports.PeraWalletConnect.eval (webpack-internal:///./node_modules/@perawallet/connect/dist/index-96895f5f.js:2:18305)\n    at Generator.next (<anonymous>)\n    at eval (webpack-internal:///./node_modules/@perawallet/connect/dist/index-96895f5f.js:2:642)\n    at new Promise (<anonymous>)\n    at s (webpack-internal:///./node_modules/@perawallet/connect/dist/index-96895f5f.js:2:387)\n    at exports.PeraWalletConnect.signTransaction (webpack-internal:///./node_modules/@perawallet/connect/dist/index-96895f5f.js:2:17885)\n    at e.eval (webpack-internal:///./node_modules/@reach-sh/stdlib/dist/browser/reachsdk.min.js:3:2362860)\n    at eval (webpack-internal:///./node_modules/@reach-sh/stdlib/dist/browser/reachsdk.min.js:3:2361552)\n    at Object.eval [as next] (webpack-internal:///./node_modules/@reach-sh/stdlib/dist/browser/reachsdk.min.js:3:2361657)\n    at s (webpack-internal:///./node_modules/@reach-sh/stdlib/dist/browser/reachsdk.min.js:3:2360371)"[[Prototype]]: `

**Comment by yasin-ce** [comment]
Reach.sh passed a flat array where signTransaction requires SignerTransaction[][], and Reach.sh is discontinued.
